name = "hokui-qb"
main = "src/index.ts"
compatibility_date = "2025-05-01"
workers_dev = true
preview_urls = false

[triggers]
crons = ["0 0 * * *"]  # 毎日0時に実行

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "hokui-qb-questions"
database_id = "d9db7a6d-e766-4efb-a293-ec390e8a7df1"
